
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;MeterStyles~~~~~~~~~~~~~~~~~~~~~~~~
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[IconStyle]
dynamicvariables=1
greyscale=#greyscale#
solidcolor=0,0,0,1
maskimagepath=#@#images\mask
AntiAlias=1
h=80
w=80

[TextStyle]
dynamicvariables=1
h=80
w=180
x=90r
y=40r
clipstring=1
fontface=#fontface#
fontsize=#fontsize#
fontcolor=#fontcolor#
stringalign=leftcenter
stringeffect=shadow
AntiAlias=1
hidden=1
Group=Labels
